site_name: Rust for Delivery Architecture
repo_url: https://github.com/reynn/rust-language
site_author: Nic Patterson
docs_dir: markdown
site_dir: docs
use_directory_urls: True
nav:
  - Home: index.md
  - Setup:
      - General: setup/general.md
      - Vim/NeoVim: setup/vim.md
      - VS Code: setup/vscode.md
  - Language Features: features.md
  - Best Practices: best_practices.md
  - Testing: testing.md
  - Documentation: documentation.md
  - Crates: crates.md
  - Cargo: cargo.md
theme:
  name: material
markdown_extensions:
  - smarty
  - toc:
      permalink: True
